import type { User, Company, Account, Transaction, CostCenter, Employee, Subject, Voucher, Purchase } from './types';

export const mockUser: User = {
  id: 'user-1',
  name: 'Alex Doe',
  email: 'alex.doe@example.com',
  avatarUrl: 'https://i.pravatar.cc/150?u=a042581f4e29026704d',
  role: 'Accountant',
};

export const mockCompanies: Company[] = [
  { id: 'com-1', name: 'Innovate Inc.', industry: 'Technology', active: true },
  { id: 'com-2', name: 'HealthFirst Solutions', industry: 'Healthcare', active: true },
  { id: 'com-3', name: 'GreenLeaf Organics', industry: 'Agriculture', active: false },
  { id: 'com-4', name: 'Constructo Corp.', industry: 'Construction', active: true },
  { id: 'com-5', name: 'Quantum Logistics', industry: 'Transport', active: true },
];

export const mockAccounts: Account[] = [
  { id: 'acc-1', code: '1', name: 'ACTIVOS', type: 'Activo', balance: 0 },
  { id: 'acc-2', code: '101', name: 'ACTIVO CORRIENTE', type: 'Activo', balance: 0 },
  { id: 'acc-3', code: '10101', name: 'EFECTIVO Y EQUIVALENTE', type: 'Activo', balance: 0 },
  { id: 'acc-4', code: '1010101', name: 'CAJA', type: 'Activo', balance: 150000.75 },
  { id: 'acc-5', code: '1010102', name: 'BANCOS', type: 'Activo', balance: 0 },
  { id: 'acc-6', code: '10102', name: 'OTROS ACT. FINANCIEROS CORR.', type: 'Activo', balance: 0 },
  { id: 'acc-7', code: '1010210', name: 'DEPOSITO A PLAZO BANCOS', type: 'Activo', balance: 0 },
  { id: 'acc-8', code: '1010220', name: 'FONDOS MUTUOS', type: 'Activo', balance: 0 },
  { id: 'acc-9', code: '10103', name: 'OTROS ACT. NO FINANCIEROS COR.', type: 'Activo', balance: 0 },
  { id: 'acc-10', code: '1010310', name: 'UTILES DE OFICINA', type: 'Activo', balance: 0 },
  { id: 'acc-11', code: '1010320', name: 'MATERIALES DE OFICINA', type: 'Activo', balance: 0 },
  { id: 'acc-12', code: '1010350', name: 'ANTICIPOS DE PROVEEDORES', type: 'Activo', balance: 0 },
  { id: 'acc-13', code: '1010351', name: 'ANTICIPOS PUBLICIDAD', type: 'Activo', balance: 0 },
  { id: 'acc-14', code: '1010352', name: 'ANTICIPOS DE HONORARIOS', type: 'Activo', balance: 0 },
  { id: 'acc-15', code: '1010353', name: 'ANTICIPOS DE SUELDOS', type: 'Activo', balance: 0 },
  { id: 'acc-16', code: '1010370', name: 'PRIMAS DE SEGURO', type: 'Activo', balance: 0 },
  { id: 'acc-17', code: '1010380', name: 'RENTAS PAGADAS POR ANTICIPADO', type: 'Activo', balance: 0 },
  { id: 'acc-18', code: '10104', name: 'DEUDORES COMER. Y OTRAS CXC', type: 'Activo', balance: 0 },
  { id: 'acc-19', code: '1010401', name: 'CLIENTES', type: 'Activo', balance: 75230.50 },
  { id: 'acc-20', code: '1010415', name: 'HONORARIOS POR COBRAR', type: 'Activo', balance: 0 },
  { id: 'acc-21', code: '1010420', name: 'ESTIMACION DEUDORES INCOBRABLE', type: 'Activo', balance: 0 },
  { id: 'acc-22', code: '1010430', name: 'CHEQUES A FECHA', type: 'Activo', balance: 0 },
  { id: 'acc-23', code: '1010431', name: 'LETRAS POR COBRAR', type: 'Activo', balance: 0 },
  { id: 'acc-24', code: '1010432', name: 'PAGARES POR COBRAR', type: 'Activo', balance: 0 },
  { id: 'acc-25', code: '1010440', name: 'OTROS DOCUMENTOS POR COBRAR', type: 'Activo', balance: 0 },
  { id: 'acc-26', code: '10105', name: 'CXC ENTIDADES REL. CORRIENTES', type: 'Activo', balance: 0 },
  { id: 'acc-27', code: '1010501', name: 'CXC EMP. RELACIONADAS', type: 'Activo', balance: 0 },
  { id: 'acc-28', code: '10106', name: 'INVENTARIOS', type: 'Activo', balance: 0 },
  { id: 'acc-29', code: '1010610', name: 'MATERIAS PRIMAS', type: 'Activo', balance: 0 },
  { id: 'acc-30', code: '1010611', name: 'MATERIALES DIRECTOS', type: 'Activo', balance: 0 },
  { id: 'acc-31', code: '1010620', name: 'PRODUCTOS EN PROCESO', type: 'Activo', balance: 0 },
  { id: 'acc-32', code: '1010621', name: 'PRODUCTOS TERMINADOS', type: 'Activo', balance: 0 },
  { id: 'acc-33', code: '1010630', name: 'MERCADERIAS NACIONALES', type: 'Activo', balance: 0 },
  { id: 'acc-34', code: '1010640', name: 'IMPORTACIONES EN TRANSITO', type: 'Activo', balance: 0 },
  { id: 'acc-35', code: '1010690', name: 'PROVISION MERCADERIA OBSOLETA', type: 'Activo', balance: 0 },
  { id: 'acc-36', code: '10107', name: 'ACTIVOS BIOLOGICOS CORRIENTES', type: 'Activo', balance: 0 },
  { id: 'acc-37', code: '1010701', name: 'ACTIVOS BIOLOGICOS CORRIentes', type: 'Activo', balance: 0 },
  { id: 'acc-38', code: '10108', name: 'ACTIVOS IMPUESTOS CORRIENTES', type: 'Activo', balance: 0 },
  { id: 'acc-39', code: '1010801', name: 'PPM', type: 'Activo', balance: 0 },
  { id: 'acc-40', code: '1010802', name: 'IVA CREDITO FISCAL', type: 'Activo', balance: 0 },
  { id: 'acc-41', code: '1010803', name: 'IVA REMANENTE CREDITO FISCAL', type: 'Activo', balance: 0 },
  { id: 'acc-42', code: '1010804', name: 'IMPUESTO ADICIONAL', type: 'Activo', balance: 0 },
  { id: 'acc-43', code: '1010805', name: 'IMPUESTO ESPECIFICO', type: 'Activo', balance: 0 },
  { id: 'acc-44', code: '1010825', name: 'RETENCION HONORARIO POR COBRAR', type: 'Activo', balance: 0 },
  { id: 'acc-45', code: '10109', name: 'ACTIVOS NO CORR. X CLASIFICAR', type: 'Activo', balance: 0 },
  { id: 'acc-46', code: '1010910', name: 'ACTIVO MANT. PARA VENTA', type: 'Activo', balance: 0 },
  { id: 'acc-47', code: '1010920', name: 'ACTIVO MANT. PARA PROPIETARIOS', type: 'Activo', balance: 0 },
  { id: 'acc-48', code: '102', name: 'ACTIVO NO CORRIENTE', type: 'Activo', balance: 0 },
  { id: 'acc-49', code: '10201', name: 'OTROS ACTIVOS FINAN. NO CORR.', type: 'Activo', balance: 0 },
  { id: 'acc-50', code: '1020101', name: 'OTROS FINANCIEROS NO CORR.', type: 'Activo', balance: 0 },
  { id: 'acc-51', code: '10202', name: 'OTROS NO FINANCIEROS NO CORR.', type: 'Activo', balance: 0 },
  { id: 'acc-52', code: '1020201', name: 'ARRIENDOS EN GARANTIA POR REC.', type: 'Activo', balance: 0 },
  { id: 'acc-53', code: '10203', name: 'DERECHOS COBRAR NO CORRIENTES', type: 'Activo', balance: 0 },
  { id: 'acc-54', code: '1020301', name: 'DEUDORES A LARGO PLAZO', type: 'Activo', balance: 0 },
  { id: 'acc-55', code: '10204', name: 'CXC A ENTIDAD REL. NO CORR.', type: 'Activo', balance: 0 },
  { id: 'acc-56', code: '1020410', name: 'CXC A EMPRESA RELACIONADA L.P', type: 'Activo', balance: 0 },
  { id: 'acc-57', code: '1020420', name: 'DXC A EMPRESA RELACIONADA L.P', type: 'Activo', balance: 0 },
  { id: 'acc-58', code: '1020430', name: 'OTROS DXC A EMP RELACIONADA LP', type: 'Activo', balance: 0 },
  { id: 'acc-59', code: '10205', name: 'INV. CONTAB. METODO PARTIC', type: 'Activo', balance: 0 },
  { id: 'acc-60', code: '1020501', name: 'INV. CONTAB. METODO PARTIC', type: 'Activo', balance: 0 },
  { id: 'acc-61', code: '10206', name: 'ACTIVOS INTANGIBLES NO PLUSV.', type: 'Activo', balance: 0 },
  { id: 'acc-62', code: '1020601', name: 'DERECHOS DE AUTOR', type: 'Activo', balance: 0 },
  { id: 'acc-63', code: '1020602', name: 'MARCA REGISTRADA', type: 'Activo', balance: 0 },
  { id: 'acc-64', code: '1020603', name: 'PATENTES', type: 'Activo', balance: 0 },
  { id: 'acc-65', code: '1020604', name: 'SOFTWARE', type: 'Activo', balance: 0 },
  { id: 'acc-66', code: '1020605', name: 'FRANQUICIAS', type: 'Activo', balance: 0 },
  { id: 'acc-67', code: '1020606', name: 'GASTOS DE CONSTITUCION', type: 'Activo', balance: 0 },
  { id: 'acc-68', code: '10207', name: 'PLUSVALIA', type: 'Activo', balance: 0 },
  { id: 'acc-69', code: '1020701', name: 'PLUSVALIA', type: 'Activo', balance: 0 },
  { id: 'acc-70', code: '10208', name: 'PROPIEDAD PLANTA Y EQUIPO', type: 'Activo', balance: 0 },
  { id: 'acc-71', code: '1020810', name: 'MAQUINARIAS Y EQUIPOS', type: 'Activo', balance: 0 },
  { id: 'acc-72', code: '1020811', name: 'DEP ACUM MAQUINARIAS Y EQUIPOS', type: 'Activo', balance: 0 },
  { id: 'acc-73', code: '1020820', name: 'MUEBLES Y UTILES', type: 'Activo', balance: 0 },
  { id: 'acc-74', code: '1020824', name: 'DEPR ACUM MUEBLES Y UTILES', type: 'Activo', balance: 0 },
  { id: 'acc-75', code: '1020825', name: 'EQUIPOS COMPUTACIONAL', type: 'Activo', balance: 0 },
  { id: 'acc-76', code: '1020830', name: 'DEPR ACUM EQUIPOS COMPUTACIONAL', type: 'Activo', balance: 0 },
  { id: 'acc-77', code: '1020831', name: 'INSTALACIONES', type: 'Activo', balance: 0 },
  { id: 'acc-78', code: '10209', name: 'DEPR ACUM INSTALACIONES', type: 'Activo', balance: 0 },
  { id: 'acc-79', code: '1020901', name: 'ACTIVOS BIOLOGICOS NO CORR.', type: 'Activo', balance: 0 },
  { id: 'acc-80', code: '10210', name: 'ACTIVOS BIOLOGICOS NO CORR.', type: 'Activo', balance: 0 },
  { id: 'acc-81', code: '1021001', name: 'PROPIEDAD DE INVERSION', type: 'Activo', balance: 0 },
  { id: 'acc-82', code: '10211', name: 'PROPIEDAD DE INVERSION', type: 'Activo', balance: 0 },
  { id: 'acc-83', code: '1021101', name: 'ACTIVOS POR IMPUESTOS DIFERIDO', type: 'Activo', balance: 0 },
  { id: 'acc-84', code: '2', name: 'PASIVOS', type: 'Pasivo', balance: 0 },
  { id: 'acc-85', code: '201', name: 'PASIVO Y PATRIMONIO', type: 'Pasivo', balance: 0 },
  { id: 'acc-86', code: '20101', name: 'PASIVO CORRIENTE', type: 'Pasivo', balance: 0 },
  { id: 'acc-87', code: '2010101', name: 'OTROS PASIVOS FINAN. CORR.', type: 'Pasivo', balance: 0 },
  { id: 'acc-88', code: '2010102', name: 'DEUDAS CON BANCOS CORTO PLAZO', type: 'Pasivo', balance: 0 },
  { id: 'acc-89', code: '2010120', name: 'LINEA DE CREDITO BANCOS', type: 'Pasivo', balance: 0 },
  { id: 'acc-90', code: '2010130', name: 'ACREEDORES POR LEASING', type: 'Pasivo', balance: 0 },
  { id: 'acc-91', code: '20102', name: 'OBLIGACIONES POR FACTORING', type: 'Pasivo', balance: 0 },
  { id: 'acc-92', code: '2010201', name: 'CXP COMERCIALES Y OTRAS CTAS', type: 'Pasivo', balance: 0 },
  { id: 'acc-93', code: '2010210', name: 'PROVEEDORES', type: 'Pasivo', balance: 0 },
  { id: 'acc-94', code: '2010211', name: 'CUENTAS POR PAGAR', type: 'Pasivo', balance: 0 },
  { id: 'acc-95', code: '2010215', name: 'PPM por Pagar', type: 'Pasivo', balance: 0 },
  { id: 'acc-96', code: '2010220', name: 'SUELDOS POR PAGAR', type: 'Pasivo', balance: 85300.00 },
  { id: 'acc-97', code: '2010225', name: 'HONORARIOS POR PAGAR', type: 'Pasivo', balance: 0 },
  { id: 'acc-98', code: '20104', name: 'IMPOSICIONES POR PAGAR', type: 'Pasivo', balance: 22150.00 },
  { id: 'acc-99', code: '2010401', name: 'CXP ENTIDAD RELACIONADA CORR.', type: 'Pasivo', balance: 0 },
  { id: 'acc-100', code: '20105', name: 'CXP ENTIDAD RELACIONADA CORR.', type: 'Pasivo', balance: 0 },
  { id: 'acc-101', code: '2010590', name: 'OTRAS PROVISIONES A C.P.', type: 'Pasivo', balance: 0 },
  { id: 'acc-102', code: '20109', name: 'PROVISIONES VARIAS', type: 'Pasivo', balance: 0 },
  { id: 'acc-103', code: '2010910', name: 'PASIVOS POR IMPUESTOS CORR.', type: 'Pasivo', balance: 0 },
  { id: 'acc-104', code: '2010925', name: 'IMPUESTO UNICO TRABAJADORES', type: 'Pasivo', balance: 7800.00 },
  { id: 'acc-105', code: '2010930', name: 'IVA DEBITO FISCAL', type: 'Pasivo', balance: 0 },
  { id: 'acc-106', code: '2010940', name: 'OTROS IMPUESTOS', type: 'Pasivo', balance: 0 },
  { id: 'acc-107', code: '2010990', name: 'RETENCION IMPUESTO HONORARIOS', type: 'Pasivo', balance: 0 },
  { id: 'acc-108', code: '20110', name: 'RETENCION INGRESO HONORARIO', type: 'Pasivo', balance: 0 },
  { id: 'acc-109', code: '2011001', name: 'PROVISION IMPUESTO A LA RENTA', type: 'Pasivo', balance: 0 },
  { id: 'acc-110', code: '20111', name: 'PASIVOS CORR. BEN. EMPLEADOS', type: 'Pasivo', balance: 0 },
  { id: 'acc-111', code: '2011101', name: 'PROVISION VACACIONES PERSONAL', type: 'Pasivo', balance: 0 },
  { id: 'acc-112', code: '2011120', name: 'OTROS PASIVOS NO FINANC. CORR.', type: 'Pasivo', balance: 0 },
  { id: 'acc-113', code: '202', name: 'INGRESOS PERCIBIDOS ADELANTADO', type: 'Pasivo', balance: 0 },
  { id: 'acc-114', code: '20201', name: 'ARRIENDOS RECIBIDOS GARANTIA', type: 'Pasivo', balance: 0 },
  { id: 'acc-115', code: '2020101', name: 'PASIVO NO CORRIENTE', type: 'Pasivo', balance: 0 },
  { id: 'acc-116', code: '20202', name: 'OTROS PASIVOS FINAN. NO CORR.', type: 'Pasivo', balance: 0 },
  { id: 'acc-117', code: '2020201', name: 'DEUDAS CON BANCOS LARGO PLAZO', type: 'Pasivo', balance: 0 },
  { id: 'acc-118', code: '20203', name: 'PASIVOS NO CORRIENTES', type: 'Pasivo', balance: 0 },
  { id: 'acc-119', code: '2020301', name: 'ACREEDORES LEASING A L.P.', type: 'Pasivo', balance: 0 },
  { id: 'acc-120', code: '2020302', name: 'CXP ENTIDAD RELAC. NO CORR.', type: 'Pasivo', balance: 0 },
  { id: 'acc-121', code: '20204', name: 'CXP EMP. RELACIONADAS L.P.', type: 'Pasivo', balance: 0 },
  { id: 'acc-122', code: '20205', name: 'CXP SOCIOS A L.P.', type: 'Pasivo', balance: 0 },
  { id: 'acc-123', code: '20206', name: 'OTRAS PROVISIONES A L.P.', type: 'Pasivo', balance: 0 },
  { id: 'acc-124', code: '2020601', name: 'PASIVOS IMPUESTOS DIFERIDOS', type: 'Pasivo', balance: 0 },
  { id: 'acc-125', code: '20207', name: 'PROVISIONES NO CORR. BEN. EMP.', type: 'Pasivo', balance: 0 },
  { id: 'acc-126', code: '3', name: 'PROVISION INDEM. AÑOS SERVICIO', type: 'Patrimonio', balance: 0 },
  { id: 'acc-127', code: '301', name: 'OTROS PASIVOS NO FINAN NO CORR', type: 'Patrimonio', balance: 0 },
  { id: 'acc-128', code: '30101', name: 'PATRIMONIO', type: 'Patrimonio', balance: 0 },
  { id: 'acc-129', code: '30102', name: 'CAPITAL EMITIDO', type: 'Patrimonio', balance: 0 },
  { id: 'acc-130', code: '302', name: 'CAPITAL SOCIAL', type: 'Patrimonio', balance: 0 },
  { id: 'acc-131', code: '30201', name: 'CAPITAL PREFERENTE', type: 'Patrimonio', balance: 0 },
  { id: 'acc-132', code: '30202', name: 'GANANCIAS ACUMULADAS', type: 'Patrimonio', balance: 0 },
  { id: 'acc-133', code: '30203', name: 'PERDIDAS ACUMULADAS', type: 'Patrimonio', balance: 0 },
  { id: 'acc-134', code: '303', name: 'UTILIDADES ACUMULADAS', type: 'Patrimonio', balance: 0 },
  { id: 'acc-135', code: '30301', name: 'PERDIDAS Y GANANCIAS EJERCICIO', type: 'Patrimonio', balance: 0 },
  { id: 'acc-136', code: '30302', name: 'CUENTAS CORRIENTES DE SOCIOS', type: 'Patrimonio', balance: 0 },
  { id: 'acc-137', code: '304', name: 'CTA CTE SOCIO 1', type: 'Patrimonio', balance: 0 },
  { id: 'acc-138', code: '305', name: 'CTA CTE SOCIO 2', type: 'Patrimonio', balance: 0 },
  { id: 'acc-139', code: '306', name: 'ACCIONES PROPIAS EN CARTERA', type: 'Patrimonio', balance: 0 },
  { id: 'acc-140', code: '30601', name: 'OTRAS PARTICIP. PATRIMONIO', type: 'Patrimonio', balance: 0 },
  { id: 'acc-141', code: '307', name: 'OTRAS RESERVAS', type: 'Patrimonio', balance: 0 },
  { id: 'acc-142', code: '308', name: 'REVALORIZACION CAPITAL PROPIO', type: 'Patrimonio', balance: 0 },
  { id: 'acc-143', code: '4', name: 'PATRIMONIO DUEÑOS CONTROLADORA', type: 'Resultado', balance: 0 },
  { id: 'acc-144', code: '401', name: 'PARTICIPACIONES NO CONTROLADOR', type: 'Resultado', balance: 0 },
  { id: 'acc-145', code: '40101', name: 'RESULTADOS', type: 'Resultado', balance: 0 },
  { id: 'acc-146', code: '4010110', name: 'ESTADO DE RESULTADOS', type: 'Resultado', balance: 0 },
  { id: 'acc-147', code: '4010120', name: 'INGRESOS ACTIVIDAD ORDINARIAS', type: 'Resultado', balance: 0 },
  { id: 'acc-148', code: '4010130', name: 'VENTAS Y SERVICIOS AFECTOS', type: 'Resultado', balance: 0 },
  { id: 'acc-149', code: '40102', name: 'VENTAS Y SERVICIOS EXENTOS', type: 'Resultado', balance: 0 },
  { id: 'acc-150', code: '4010210', name: 'EXPORTACIONES', type: 'Resultado', balance: 0 },
  { id: 'acc-151', code: '4010220', name: 'COSTO DE VENTAS', type: 'Resultado', balance: 0 },
  { id: 'acc-152', code: '4010230', name: 'COSTO VENTAS AFECTAS', type: 'Resultado', balance: 0 },
  { id: 'acc-153', code: '4010250', name: 'COSTO VENTAS EXENTAS', type: 'Resultado', balance: 0 },
  { id: 'acc-154', code: '40105', name: 'COSTO EXPORTACIONES', type: 'Resultado', balance: 0 },
  { id: 'acc-155', code: '40106', name: 'COSTOS DE COMISION EN VENTAS', type: 'Resultado', balance: 0 },
  { id: 'acc-156', code: '4010601', name: 'UTILIDAD BRUTA', type: 'Resultado', balance: 0 },
  { id: 'acc-157', code: '40107', name: 'OTROS INGRESOS', type: 'Resultado', balance: 0 },
  { id: 'acc-158', code: '4010701', name: 'OTROS INGRESOS, POR FUNCION', type: 'Resultado', balance: 0 },
  { id: 'acc-159', code: '40108', name: 'COSTOS DE DISTRIBUCION', type: 'Resultado', balance: 0 },
  { id: 'acc-160', code: '4010810', name: 'MOVILIZACION', type: 'Resultado', balance: 0 },
  { id: 'acc-161', code: '4010812', name: 'GASTOS DE ADMINISTRACION', type: 'Resultado', balance: 0 },
  { id: 'acc-162', code: '4010813', name: 'GASTOS DE SUELDOS Y SALARIOS', type: 'Resultado', balance: 100000.00 },
  { id: 'acc-163', code: '4010814', name: 'GASTOS DE FONASA E ISAPRE', type: 'Resultado', balance: 0 },
  { id: 'acc-164', code: '4010815', name: 'GASTOS DE AFC EMPLEADOR', type: 'Resultado', balance: 0 },
  { id: 'acc-165', code: '4010816', name: 'GASTOS DE SEGURO DE INVALIDEZ', type: 'Resultado', balance: 0 },
  { id: 'acc-166', code: '4010817', name: 'GASTOS DE SEGURO ACCIDENTE', type: 'Resultado', balance: 15250.00 },
  { id: 'acc-167', code: '4010822', name: 'GASTOS DE MOVILIZACION', type: 'Resultado', balance: 0 },
  { id: 'acc-168', code: '4010890', name: 'GASTOS DE COLACION', type: 'Resultado', balance: 0 },
  { id: 'acc-169', code: '40109', name: 'BONOS Y OTROS', type: 'Resultado', balance: 0 },
  { id: 'acc-170', code: '4010915', name: 'HONORARIOS', type: 'Resultado', balance: 0 },
  { id: 'acc-171', code: '4010916', name: 'GASTOS GENERALES', type: 'Resultado', balance: 0 },
  { id: 'acc-172', code: '4010917', name: 'GASTOS DE MANTENIMIENTO Y REP', type: 'Resultado', balance: 0 },
  { id: 'acc-173', code: '40110', name: 'GASTOS DE MANTENIMIENTOS Y REP', type: 'Resultado', balance: 0 },
  { id: 'acc-174', code: '4011010', name: 'OTROS GASTOS, POR FUNCION', type: 'Resultado', balance: 0 },
  { id: 'acc-175', code: '4011020', name: 'GASTOS DE MANTENIMIENTO Y REP', type: 'Resultado', balance: 0 },
  { id: 'acc-176', code: '40120', name: 'OTRAS GANANCIAS (PERDIDAS)', type: 'Resultado', balance: 0 },
  { id: 'acc-177', code: '40121', name: 'OTRAS GANANCIAS', type: 'Resultado', balance: 0 },
  { id: 'acc-178', code: '4012110', name: 'OTRAS PERDIDAS', type: 'Resultado', balance: 0 },
  { id: 'acc-179', code: '40122', name: 'GANANCIAS (PERDIDAS) ACT. OP.', type: 'Resultado', balance: 0 },
  { id: 'acc-180', code: '4012210', name: 'INGRESOS FINANCIEROS', type: 'Resultado', balance: 0 },
  { id: 'acc-181', code: '40124', name: 'INTERESES GANADOS', type: 'Resultado', balance: 0 },
  { id: 'acc-182', code: '40125', name: 'COSTOS FINANCIEROS', type: 'Resultado', balance: 0 },
  { id: 'acc-183', code: '4012501', name: 'COSTOS FINANCIEROS', type: 'Resultado', balance: 0 },
  { id: 'acc-184', code: '4012570', name: 'DIFERENCIAS DE CAMBIO', type: 'Resultado', balance: 0 },
  { id: 'acc-185', code: '4012590', name: 'DIFERENCIAS DE CAMBIO', type: 'Resultado', balance: 0 },
  { id: 'acc-186', code: '40190', name: 'RESULTADOS UNIDADES REAJUSTE', type: 'Resultado', balance: 0 },
  { id: 'acc-187', code: '40191', name: 'REAJUSTE CREDITO IVA y PPM', type: 'Resultado', balance: 0 },
  { id: 'acc-188', code: '4019101', name: 'REAJUSTE ACTIVOS EN UF', type: 'Resultado', balance: 0 },
  { id: 'acc-189', code: '40192', name: 'REAJUSTE PASIVOS EN UF', type: 'Resultado', balance: 0 },
  { id: 'acc-190', code: '40193', name: 'GANANCIAS (PERDIDAS) ANTES IMP', type: 'Resultado', balance: 0 },
  { id: 'acc-191', code: '4019310', name: 'GASTO POR IMPUESTO GANANCIAS', type: 'Resultado', balance: 0 },
  { id: 'acc-192', code: '4019320', name: 'IMPUESTO A LA RENTA', type: 'Resultado', balance: 0 },
  { id: 'acc-193', code: '40199', name: 'GANANCIAS (PERDIDAS) OP. CONT.', type: 'Resultado', balance: 0 },
];


export const mockTransactions: Transaction[] = [
    { id: 'txn-1', date: '2023-10-28', description: 'Client payment for Project X', amount: 15000, type: 'Credit', account: 'Service Revenue', status: 'Completed' },
    { id: 'txn-2', date: '2023-10-27', description: 'October salaries', amount: 25000, type: 'Debit', account: 'Salaries Expense', status: 'Completed' },
    { id: 'txn-3', date: '2023-10-26', description: 'Invoice #INV-003 from Supplier Co.', amount: 3200, type: 'Debit', account: 'Accounts Payable', status: 'Pending' },
    { id: 'txn-4', date: '2023-10-25', description: 'Cash withdrawal for petty cash', amount: 500, type: 'Debit', account: 'Cash', status: 'Completed' },
    { id: 'txn-5', date: '2023-10-24', description: 'Received payment for Invoice #INV-001', amount: 7500, type: 'Credit', account: 'Accounts Receivable', status: 'Completed' },
    { id: 'txn-6', date: '2023-10-23', description: 'Cloud server hosting - October', amount: 450, type: 'Debit', account: 'Utilities Expense', status: 'Failed' },
];

export const mockCostCenters: CostCenter[] = [
    { id: 'cc-1', name: 'Producción', description: 'Costos asociados a la línea de producción.' },
    { id: 'cc-2', name: 'Administración', description: 'Costos generales y de administración.' },
    { id: 'cc-3', name: 'Ventas y Marketing', description: 'Costos relacionados con la comercialización y venta de productos.' },
];

export const mockEmployees: Employee[] = [
  { id: 'emp-1', name: 'Juan Pérez', rut: '12.345.678-9', position: 'Operario de Producción', costCenter: 'Producción', status: 'Active' },
  { id: 'emp-2', name: 'Ana Gómez', rut: '9.876.543-2', position: 'Asistente Administrativa', costCenter: 'Administración', status: 'Active' },
  { id: 'emp-3', name: 'Carlos Soto', rut: '15.678.901-K', position: 'Vendedor', costCenter: 'Ventas y Marketing', status: 'Active' },
  { id: 'emp-4', name: 'María Rodríguez', rut: '18.123.456-7', position: 'Jefe de Producción', costCenter: 'Producción', status: 'Inactive' },
];

export const mockSubjects: Subject[] = [
    { id: 'sub-1', name: 'Comercial ABC Ltda.', rut: '76.123.456-7', type: 'Cliente', status: 'Active' },
    { id: 'sub-2', name: 'Proveedor de Servicios XYZ S.A.', rut: '77.987.654-3', type: 'Proveedor', status: 'Active' },
    { id: 'sub-3', name: 'Asesorías Profesionales SpA', rut: '78.456.123-K', type: 'Proveedor', status: 'Active' },
    { id: 'sub-4', name: 'Cliente Minorista Ejemplo', rut: '15.890.123-4', type: 'Cliente', status: 'Inactive' },
];

export const mockVouchers: Voucher[] = [
    { id: 'v-1', date: '2023-11-01', type: 'Ingreso', description: 'Pago factura #101', status: 'Posteado', total: 125000 },
    { id: 'v-2', date: '2023-11-02', type: 'Egreso', description: 'Pago de arriendo oficina', status: 'Posteado', total: 550000 },
    { id: 'v-3', date: '2023-11-03', type: 'Traspaso', description: 'Ajuste de caja', status: 'Borrador', total: 15000 },
    { id: 'v-4', date: '2023-11-04', type: 'Egreso', description: 'Compra de suministros', status: 'Posteado', total: 75000 },
    { id: 'v-5', date: '2023-11-05', type: 'Ingreso', description: 'Abono cliente Z', status: 'Posteado', total: 200000 },
];

export const mockPurchases: Purchase[] = [
    { id: 'pur-1', date: '2023-11-01', documentNumber: 'F-8765', supplier: 'Proveedor de Servicios XYZ S.A.', total: 450000, status: 'Pagada' },
    { id: 'pur-2', date: '2023-11-05', documentNumber: 'F-8766', supplier: 'Comercial ABC Ltda.', total: 120000, status: 'Pendiente' },
    { id: 'pur-3', date: '2023-10-15', documentNumber: 'F-8750', supplier: 'Proveedor de Servicios XYZ S.A.', total: 300000, status: 'Vencida' },
    { id: 'pur-4', date: '2023-11-10', documentNumber: 'BH-123', supplier: 'Asesorías Profesionales SpA', total: 85000, status: 'Pendiente' },
];
