 
// src/lib/previred-fields.ts
export const PREVIRED_FIELDS = [
    { id: 1, name: 'RUT Trabajador' },
    { id: 2, name: 'DV Trabajador' },
    { id: 3, name: 'Apellido Paterno' },
    { id: 4, name: 'Apellido Materno' },
    { id: 5, name: 'Nombres' },
    { id: 6, name: 'Sexo' },
    { id: 7, name: 'Nacionalidad' },
    { id: 8, name: 'Tipo Pago' },
    { id: 9, name: 'Período Desde' },
    { id: 10, name: 'Período Hasta' },
    { id: 11, name: 'Régimen Previsional' },
    { id: 12, name: 'Tipo Trabajador' },
    { id: 13, name: 'Días Trabajados' },
    { id: 14, name: 'Tipo de Línea' },
    { id: 15, name: 'Código Movimiento' },
    { id: 16, name: 'Fecha Desde' },
    { id: 17, name: 'Fecha Hasta' },
    { id: 18, name: 'Tramo Asignación Familiar' },
    { id: 19, name: 'N° Cargas Simples' },
    { id: 20, name: 'N° Cargas Maternales' },
    { id: 21, name: 'N° Cargas Inválidas' },
    { id: 22, name: 'Asignación Familiar' },
    { id: 23, name: 'Asignación Familiar Retroactiva' },
    { id: 24, name: 'Reintegro Cargas Familiares' },
    { id: 25, name: 'Solicitud Trabajador Joven' },
    { id: 26, name: 'Código AFP' },
    { id: 27, name: 'Renta Imponible AFP' },
    { id: 28, name: 'Cotización Obligatoria AFP' },
    { id: 29, name: 'Cotización SIS' },
    { id: 30, name: 'Ahorro Voluntario AFP (APVI)' },
    { id: 31, name: 'Renta Imp. Sustitutiva' },
    { id: 32, name: 'Tasa Pactada Sustitutiva' },
    { id: 33, name: 'Aporte Voluntario' },
    { id: 34, name: 'Número de Períodos' },
    { id: 35, name: 'Código de la APVI' },
    { id: 36, name: 'Forma de Pago APVI' },
    { id: 37, name: 'Monto APVI' },
    { id: 38, name: 'Código Institución de Salud' },
    { id: 39, name: 'Número FUN' },
    { id: 40, name: 'Renta Imponible Salud' },
    { id: 41, name: 'Cotización Obligatoria Salud' },
    { id: 42, name: 'Cotización Adicional Voluntaria' },
    { id: 43, name: 'Monto Garantía Explícita en Salud (GES)' },
    { id: 44, name: 'Moneda Plan Pactado' },
    { id: 45, name: 'Monto Plan Pactado' },
    { id: 46, name: 'Código CCAF' },
    { id: 47, name: 'Renta Imponible CCAF' },
    { id: 48, name: 'Créditos Personales CCAF' },
    { id: 49, name: 'Descuento por Leasing' },
    { id: 50, name: 'Otros descuentos CCAF' },
    { id: 51, name: 'Cotización CCAF' },
    { id: 52, name: 'Renta Imponible Seguro Cesantía' },
    { id: 53, name: 'Aporte Trabajador Seguro Cesantía' },
    { id: 54, name: 'Aporte Empleador Seguro Cesantía' },
    { id: 55, name: 'Código Mutual' },
    { id: 56, name: 'Renta Imponible Mutual' },
    { id: 57, name: 'Cotización Accidente del Trabajo' },
    { id: 58, name: 'Sucursal' },
    { id: 59, name: 'Renta Imponible IPS' },
    { id: 60, name: 'Cotización Obligatoria IPS' },
    { id: 61, name: 'Bonificación Ley 15.386' },
    { id: 62, name: 'Descuento por Cotización de Pensionados' },
    { id: 63, name: 'Descuentos por Salud' },
    { id: 64, name: 'Aporte Patronal ex INP' },
    { id: 65, name: 'Otros Aportes Patronales ex INP' },
    { id: 66, name: 'Código Sucursal' },
    { id: 67, name: 'Renta Imponible para Seguro de Cesantía de Afiliado Voluntario' },
    { id: 68, name: 'Monto Cotización para Seguro de Cesantía de Afiliado Voluntario' },
    { id: 69, name: 'Renta Imponible para Subsidio por Incapacidad Laboral' },
    { id: 70, name: 'Monto del Subsidio (pago empresa)' },
    { id: 71, name: 'Número de días de Licencia Médica' },
    { id: 72, name: 'Tipo de Licencia' },
    { id: 73, name: 'Monto de Cotización Adicional (Subsidio)' },
    { id: 74, name: 'Monto de Cotización para Salud (Subsidio)' },
    { id: 75, name: 'Monto de Cotización para Seguro de Cesantía (Subsidio)' },
    { id: 76, name: 'Monto de Cotización para CCAF (Subsidio)' },
    { id: 77, name: 'Monto de Cotización para Mutual (Subsidio)' },
    { id: 78, name: 'Monto de Cotización para Ahorro Previsional Voluntario Individual (Subsidio)' },
    { id: 79, name: 'Monto de Cotización para Ahorro Previsional Voluntario Colectivo (Subsidio)' },
    { id: 80, name: 'RUT del Afiliado Voluntario' },
    { id: 81, name: 'DV del Afiliado Voluntario' },
    { id: 82, name: 'Apellido Paterno del Afiliado Voluntario' },
    { id: 83, name: 'Apellido Materno del Afiliado Voluntario' },
    { id: 84, name: 'Nombres del Afiliado Voluntario' },
    { id: 85, name: 'Sexo del Afiliado Voluntario' },
    { id: 86, name: 'Nacionalidad del Afiliado Voluntario' },
    { id: 87, name: 'Código de la Entidad Pagadora de Subsidio' },
    { id: 88, name: 'Monto Total Pago de Subsidio' },
    { id: 89, name: 'Renta Imponible para Seguro de Cesantía de Trabajador de Casa Particular' },
    { id: 90, name: 'Aporte del Trabajador para Seguro de Cesantía de Trabajador de Casa Particular' },
    { id: 91, name: 'Aporte del Empleador para Seguro de Cesantía de Trabajador de Casa Particular' },
    { id: 92, name: 'Aporte de Indemnización de Trabajador de Casa Particular' },
    { id: 93, name: 'RUT del Mandante' },
    { id: 94, name: 'DV del Mandante' },
    { id: 95, name: 'Monto Total de la Obra' },
    { id: 96, name: 'Porcentaje de Participación del Trabajador' },
    { id: 97, name: 'Renta Imponible para FONASA' },
    { id: 98, name: 'Monto de Cotización para FONASA' },
    { id: 99, name: 'Monto de Bonificación Ley 15.386' },
    { id: 100, name: 'Monto de Descuento por Cotización de Pensionados' },
    { id: 101, name: 'Monto de Aporte Patronal ex INP' },
    { id: 102, name: 'Monto de Otros Aportes Patronales ex INP' },
    { id: 103, name: 'Monto del Ahorro Colectivo' },
    { id: 104, name: 'Número de Horas Semanales' },
    { id: 105, name: 'Código de la Sucursal de la Obra o Faena' }
];
